### ISSUE TITLE
Language isn't showing up in options

### ISSUE THREAD

**Issue by TowerOfAngels** [SFGrenade/LanguageSupport#10]
I did as readme states, 
![MainMenu - Notepad 12_14_2024 7_00_35 PM](https://github.com/user-attachments/assets/7a6a2708-673b-469e-a909-cff83b5c7b56)
but the language doesn't show up in list when i start the game.
![Hollow Knight 2024-12-14 18-59-09](https://github.com/user-attachments/assets/c0fa3315-24a0-44dc-8053-eb09cde4f354)
Did I make some kind of mistake?
Used Scarab v.2.6.0.0

**Comment by SFGrenade** [comment]
uh, which language is `by` supposed to be?

**Comment by TowerOfAngels** [comment]
It's supposed to be Belarusian. I tried making translation a couple of days ago, but met the same problem. Then i reinstalled scarab and mod, translated a couple of texts (Elderbug and achievements) and tried to test it.

**Comment by SFGrenade** [comment]
try `LANG_BE` then, not `LANG_BY`
and the folder with `BE` instead of `BY` as well

**Comment by TowerOfAngels** [comment]
Oh! It worked! Thanks a lot!
