### ISSUE TITLE
Mod doesn't work with 1.4.3.2 and UA language

### ISSUE THREAD

**Issue by SLoN1ck** [SFGrenade/LanguageSupport#3]
Version: 1.4.3.2 (the only version in which I'm able to run mod installer).

1) I've performed readme "Making additional translations" instructions and added UA language (tried CZ as well).
2) After performing those steps I got **two English languages** in menu, and no matter what I change in my folders under both
C:\Program Files (x86)\Steam\steamapps\common\Hollow Knight\hollow_knight_Data\Managed\Mods\LanguageSupport\UA
C:\Program Files (x86)\Steam\steamapps\common\Hollow Knight\hollow_knight_Data\Managed\Mods\LanguageSupport\EN
nothing is changed in game - new language is not shown, and texts are not updating

Please see the recording:
![WF4uWXfqOT](https://user-images.githubusercontent.com/6781574/131547508-6ce14a04-66d2-45da-ac4c-05b9f63687a7.gif)
and configuration:
![image](https://user-images.githubusercontent.com/6781574/131547322-410c240f-0318-4793-b966-234b486b9297.png)

Also worth mentioning - I've noticed the size of DLL is only 9 KB, while DLL size of latest tags on Github is much bigger. Manual substitution of latest tag (1.5.0) DLL file gives me an error
![hollow_knight_0GnIGT4qjC](https://user-images.githubusercontent.com/6781574/131547718-b6afed72-53cd-4cc0-9f85-0f01615e85d2.png)

Any help will be greatly appreciated, I'm striving to create UA translation very much!

**Comment by SFGrenade** [comment]
answering the most abvious first: latest github is for the 1.5 patches of the game, not the one the current modinstaller is for.

For the not showing up: the language code for ukranian is `UK`.

**Comment by SLoN1ck** [comment]
Amazing... I thought UK would be for United Kingdom English or something like that. 
And of couse I used CZ instead of CS (which is most likely not correct code)... 

Thank you very much for your fast reply. Mod is working now! You've made my evening!
