### ISSUE TITLE
the creation of new language doesnt work

### ISSUE THREAD

**Issue by kiwioGIT** [SFGrenade/LanguageSupport#4]
the language just doesnt load when i do exactly what is in the readme
...
![OnPaste 20211207-185041](https://user-images.githubusercontent.com/67319505/145081427-ceae8518-eb4c-4b71-993f-b18c0fd30ba9.png)
....
but when i select the language the text isnt loaded
....
![OnPaste 20211207-185232](https://user-images.githubusercontent.com/67319505/145081640-c22c7850-7232-4b3c-ba2a-cdf05264d3e8.png)

![OnPaste 20211207-185344](https://user-images.githubusercontent.com/67319505/145081653-25a83069-2f9f-426c-bdbe-cc1e339163fd.png)

**Comment by SFGrenade** [comment]
late answer, but can you try it with the latest version that is on scarab?

**Comment by MikeCZ23** [comment]
language is loaded, but textures of shops etc. are not loaded

**Comment by SFGrenade** [comment]
> but textures of shops etc. are not loaded

uhm, what exactly do you mean by that? this mod is only for translating text (or well, in the case of shops also prices), not for editing sprites.

**Comment by MikeCZ23** [comment]
I mean that after activating the mod my shop ui disappears, the icons that I can sit or trade are not there, the npc conversations are just black bubbles with no text.

Sorry for my English. I use deepL

**Comment by SFGrenade** [comment]
i will take a look at this. thanks and i hope i get good results very soon!

**Comment by SFGrenade** [comment]
oh, that was my error while i attempted to get languages with custom characters working.
I'll upload a working version in the next few minutes!
